- block:

  - name: exist awscli v2
    command: which aws
    register: result
    changed_when: no
    failed_when: no

  - block:

    - name: download awscli installer
      get_url:
        url: https://awscli.amazonaws.com/AWSCLIV2.pkg
        dest: /tmp/AWSCLIV2.pkg
        validate_certs: no
      register: download

    - name: install awscli
      become: yes
      command: "installer -pkg {{ download.dest }} -target /"

    when: result.rc == 1

  - name: add completion to .zshrc
    lineinfile:
      path: ~/.zshrc
      line: complete -C aws_completer aws

  tags:
    - awscli
