homebrew_taps:
  - homebrew/cask
  - homebrew/core
homebrew_packages:
  - name: ansible
  - name: git
  - name: zsh
  - name: wget
  - name: tmux
  - name: go
homebrew_cask_packages:
  # - name: google-chrome
  # - name: slack
  - name: visual-studio-code
code_extensions:
  - name: golang.go
  - name: AquaSecurityOfficial.trivy-vulnerability-scanner
