homebrew_taps:
  - homebrew/cask
  - homebrew/core
homebrew_packages:
  - name: ansible
  - name: git
  - name: zsh
  - name: zsh-autosuggestions
  - name: zsh-syntax-highlighting
  - name: zsh-completions
  - name: zsh-completion
  #- name: coreutils
  - name: tree
  - name: peco
  - name: vim
  - name: wget
  # - name: tmux
  - name: tree
  - name: gnu-sed
  - name: awk
  - name: jq
  - name: direnv
  - name: anyenv
  - name: pwgen
  - name: terraformer
  - name: packer
  - name: golangci/tap/golangci-lint
  - name: bash
  - name: gnu-tar
  - name: aquasecurity/trivy/trivy
  - name: go
  - name: lima
  - name: docker
  - name: colima
  - name: gh
  - name: fujiwara/tap/lambroll
homebrew_cask_packages:
  # - name: google-chrome
  # - name: slack
  - name: iterm2
  - name: visual-studio-code
  - name: aws-vault
  - name: google-cloud-sdk
code_extensions:
  - name: golang.go
  - name: 766b.go-outliner
  - name: msyrus.go-doc
  - name: ms-vsliveshare.vsliveshare
  - name: ms-azuretools.vscode-docker
  - name: 42Crunch.vscode-openapi
  - name: Gruntfuggly.todo-tree
  - name: yzhang.markdown-all-in-one
  - name: bierner.markdown-emoji
  - name: GitHub.vscode-pull-request-github
  - name: redhat.vscode-yaml
  - name: AquaSecurityOfficial.trivy-vulnerability-scanner
