homebrew_taps:
  - hashicorp/tap
homebrew_packages:
  - name: ansible
  - name: git
  - name: zsh
  - name: zsh-autosuggestions
  - name: zsh-syntax-highlighting
  - name: zsh-completions
  - name: zsh-completion
  #- name: coreutils
  - name: tree
  - name: peco
  - name: vim
  - name: wget
  # - name: tmux
  - name: gnu-sed
  - name: awk
  - name: jq
  - name: direnv
  - name: anyenv
  - name: pwgen
  - name: bash
  - name: gnu-tar
  - name: lima
  - name: docker
  - name: docker-compose
  - name: docker-buildx
  - name: colima
  - name: gh
  - name: go
  - name: hashicorp/tap/terraform
homebrew_cask_packages:
  - name: google-chrome
  - name: slack
  - name: iterm2
  - name: visual-studio-code
  - name: aws-vault
  - name: google-cloud-sdk
  - name: pritunl
  - name: gather
  - name: kindle
  - name: zoom
  - name: tableplus
code_extensions:
  - name: golang.go
  - name: xmtt.go-mod-grapher
  - name: 766b.go-outliner
  - name: msyrus.go-doc
  - name: ms-vsliveshare.vsliveshare
  - name: ms-azuretools.vscode-docker
  - name: 42Crunch.vscode-openapi
  - name: Gruntfuggly.todo-tree
  - name: yzhang.markdown-all-in-one
  - name: bierner.markdown-emoji
  - name: GitHub.vscode-pull-request-github
  - name: redhat.vscode-yaml
  - name: AquaSecurityOfficial.trivy-vulnerability-scanner
  - name: github.copilot
  - name: github.copilot-chat
  - name: eamodio.gitlens
  - name: hashicorp.terraform
  - name: hediet.vscode-drawio
  - name: mhutchie.git-graph
  - name: bierner.markdown-mermaid
  - name: codestream.codestream
  - name: jflbr.jwt-decoder
  - name: khaeransori.json2csv
  - name: humao.rest-client
  - name: formulahendry.vscode-mysql
  - name: ms-ossdata.vscode-postgresql
